import React from 'react';
import { DiagnosticsReport, SystemStatus } from '../types';
import { Activity, AlertTriangle, CheckCircle, Clock, Cpu } from 'lucide-react';

interface DiagnosticsPanelProps {
  report: DiagnosticsReport | null;
  loading: boolean;
  onRunDiagnostics: () => void;
}

const DiagnosticsPanel: React.FC<DiagnosticsPanelProps> = ({ report, loading, onRunDiagnostics }) => {
  
  const getStatusColor = (status: SystemStatus) => {
    switch(status) {
      case SystemStatus.NOMINAL: return "text-emerald-400 border-emerald-500/30 bg-emerald-950/20";
      case SystemStatus.WARNING: return "text-amber-400 border-amber-500/30 bg-amber-950/20";
      case SystemStatus.CRITICAL: return "text-rose-500 border-rose-500/30 bg-rose-950/20";
      default: return "text-slate-400 border-slate-700 bg-slate-800";
    }
  };

  const getStatusIcon = (status: SystemStatus) => {
    switch(status) {
      case SystemStatus.NOMINAL: return <CheckCircle className="w-6 h-6" />;
      case SystemStatus.WARNING: return <AlertTriangle className="w-6 h-6" />;
      case SystemStatus.CRITICAL: return <Activity className="w-6 h-6 animate-pulse" />;
      default: return <Cpu className="w-6 h-6" />;
    }
  };

  return (
    <div className="h-full flex flex-col bg-slate-800/80 rounded-lg border border-slate-600 p-6 shadow-xl relative overflow-hidden">
      {/* Decorative tech lines */}
      <div className="absolute top-0 right-0 p-2 opacity-20">
        <div className="flex gap-1">
          <div className="w-2 h-2 bg-cyan-500 rounded-full"></div>
          <div className="w-2 h-2 bg-cyan-500 rounded-full"></div>
          <div className="w-2 h-2 bg-cyan-500 rounded-full"></div>
        </div>
      </div>

      <div className="flex justify-between items-center mb-6">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <Cpu className="text-cyan-400" />
          AI DIAGNOSTICS
        </h2>
        <button
          onClick={onRunDiagnostics}
          disabled={loading}
          className={`
            px-4 py-2 rounded font-mono text-sm font-bold uppercase tracking-wide transition-all
            ${loading 
              ? 'bg-slate-700 text-slate-400 cursor-not-allowed' 
              : 'bg-cyan-600 hover:bg-cyan-500 text-white shadow-[0_0_15px_rgba(8,145,178,0.5)] border border-cyan-400'
            }
          `}
        >
          {loading ? 'Analyzing...' : 'Run Analysis'}
        </button>
      </div>

      <div className="flex-grow space-y-4 font-mono">
        {!report ? (
          <div className="h-full flex flex-col items-center justify-center text-slate-500 space-y-4 opacity-60">
            <Activity className="w-16 h-16" />
            <p>System ready for diagnostics.</p>
            <p className="text-xs max-w-xs text-center">Initiate scan to analyze telemetry data for anomalies and efficiency ratings.</p>
          </div>
        ) : (
          <>
            <div className={`p-4 rounded border flex items-center gap-4 ${getStatusColor(report.status)}`}>
              {getStatusIcon(report.status)}
              <div>
                <div className="text-xs uppercase opacity-70">System Status</div>
                <div className="text-2xl font-bold tracking-widest">{report.status}</div>
              </div>
            </div>

            <div className="space-y-4 mt-4">
              <div className="bg-slate-900/50 p-4 rounded border border-slate-700">
                <h4 className="text-cyan-400 text-xs uppercase mb-2">Technical Analysis</h4>
                <p className="text-sm leading-relaxed text-slate-300">{report.analysis}</p>
              </div>

              <div className="bg-slate-900/50 p-4 rounded border border-slate-700">
                <h4 className="text-cyan-400 text-xs uppercase mb-2">Recommendation</h4>
                <p className="text-sm leading-relaxed text-slate-300">{report.recommendation}</p>
              </div>

              {report.estimatedTimeUntilFailure && report.estimatedTimeUntilFailure !== 'N/A' && (
                 <div className="bg-rose-950/20 p-3 rounded border border-rose-900/50 flex items-center gap-3">
                   <Clock className="w-5 h-5 text-rose-500" />
                   <div>
                      <div className="text-rose-500 text-xs uppercase">Est. Time to Critical</div>
                      <div className="text-rose-200 text-sm">{report.estimatedTimeUntilFailure}</div>
                   </div>
                 </div>
              )}
            </div>
            
            <div className="mt-auto pt-4 text-xs text-slate-600 border-t border-slate-800 text-center">
              Generated by Gemini 2.5 Flash • {new Date().toLocaleTimeString()}
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default DiagnosticsPanel;